CREATE TABLE UNIT (
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  cost INT NOT NULL,
  origin VARCHAR(255) NOT NULL,
  url_img VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;