CREATE TABLE UNIT (
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  cost INT NOT NULL,
  url_img VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE ORIGIN (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  url_img VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE UNIT_ORIGIN (
  id_unit VARCHAR(255),
  id_origin BIGINT,
  PRIMARY KEY (id_unit, id_origin),
  FOREIGN KEY (id_unit) REFERENCES UNIT(id) ON DELETE CASCADE,
  FOREIGN KEY (id_origin) REFERENCES ORIGIN(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;